name: build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qt6-base-dev qt6-5compat-dev qt6-charts-dev libopencv-dev ninja-build libxkbcommon-dev
      - name: Configure
        run: cmake --preset linux-release
      - name: Build
        run: cmake --build --preset linux-release
